### ISSUE TITLE
Request: Release and add f-droid support

### ISSUE THREAD

**Issue by cajeiri** [amirulzin/Kirinmaru#6]
Hello.

I would like to ask whether there will be any of these at any point in time:
1. An official release, either through Github or another platform.
2. Making the app available in F-Droid.

**Comment by amirulzin** [comment]
Hi,

I'll look into it once a proper stable release can be achieved and the major bugs are ironed out.
It's not fully stable yet at the moment.

As for the platform, it'll most likely be under F-Droid

**Comment by roshavagarga** [comment]
Thank you for the information :)
